# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Greeter
description: Greeter indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
    - name: KHYPE
      abi_file_path: ./abis/khype.json
      handler: ./src/KhypeEventHandlers.ts
      events:
          - event: Transfer
networks:
    - id: 645749 # Hyperliquid Mainnet
      start_block: 0
      contracts:
          - name: KHYPE
            address: 0xfD739d4e423301CE9385c1fb8850539D657C296D
          # - name: StakingManager
          #   address:
unordered_multichain_mode: true
raw_events: true
