# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Greeter
description: Greeter indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
    # - name: KHYPE
    #   abi_file_path: ./abis/khype.json
    #   handler: ./src/EventHandlers.ts
    #   events:
    #       - event: Transfer
    - name: ValidatorManager
      abi_file_path: ./abis/ValidatorManager.json
      handler: ./src/EventHandlers.ts
      events:
          - event: ValidatorActivated
          - event: ValidatorDeactivated
          - event: ValidatorReactivated
          - event: RewardEventReported
          - event: SlashingEventReported
    - name: StakingManager
      abi_file_path: ./abis/StakingManager.json
      handler: ./src/EventHandlers.ts
      events:
          # validator un/delegation events
          - event: EmergencyWithdrawalExecuted
          - event: L1DelegationProcessed
          - event: Delegate
          - event: ValidatorWithdrawal
    - name: StakingAccountant
      abi_file_path: ./abis/StakingAccountant.json
      handler: ./src/EventHandlers.ts
      events:
          # staking account events
          - event: StakingManagerAuthorized
networks:
    - id: 645749 # Hyperliquid Mainnet
      start_block: 0
      contracts:
          # - name: KHYPE
          #   address: 0xfD739d4e423301CE9385c1fb8850539D657C296D
          - name: ValidatorManager
            address: 0x4b797A93DfC3D18Cf98B7322a2b142FA8007508f
          - name: StakingManager
            address: 0x393D0B87Ed38fc779FD9611144aE649BA6082109
          - name: StakingAccountant
            address: 0x9209648Ec9D448EF57116B73A2f081835643dc7A
unordered_multichain_mode: true
raw_events: true
